### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by arvl130** [arvl130/cinemate-mobile-app#1]
Screens that we need:
- [x] Sign In (Geulin)
- [ ] Sign Up (Geulin)
- [ ] Home (Geulin)
- [ ] Search (Geulin)
- [ ] Movie Details (Carza)
- [ ] Account Settings (Carza)
- [ ] Forgot Password (Carza)
